volumes:
  menu-db-storage:

services:
  valkey-cache:
    build: "./valkey"
    restart: on-failure
    environment:
      VALKEY_PASSWORD: password
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - path: "./valkey"
          action: rebuild

  menu-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: menu
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U database -d menu" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - menu-db-storage:/var/lib/postgresql/data/

  menu-api:
    build: "./menu"
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:password@menu-db:5432/menu?sslmode=disable
      MIGRATIONS_PATH: file://./migrations
      DATABASE_MAX_IDLE_CONNS: 10
      DATABASE_MAX_OPEN_CONNS: 10
      DATABASE_MAX_IDLE_TIME: 10m
      DATABASE_MAX_LIFETIME: 10m

      VALKEY_URL: valkey://:password@valkey-cache:6379

      RATE_LIMIT_COUNT: 15
      RATE_LIMIT_WINDOW: 1s

      ADDR: 0.0.0.0:8080
      ENVIRONMENT: development
    depends_on:
      valkey-cache:
        condition: service_healthy
      menu-db:
        condition: service_healthy
    develop:
      watch:
        - path: "./menu"
          action: rebuild

  caddy-proxy:
    build: "./caddy"
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      MENU_SERVICE_ADDR: menu-api:8080
    depends_on:
      - menu-api
    develop:
      watch:
        - path: "./caddy"
          action: rebuild