version: '3'

vars:
  MIGRATIONS_PATH: "./internal/adapter/storage/postgres/migrations"
  SEEDS_PATH: "./internal/adapter/storage/postgres/seeds"

dotenv:
  - .env

tasks:
  migrate-up:
    desc: "Applies all pending migrations."
    summary: |
      Applies all pending migrations.
      
      Please make sure you have set MIGRATIONS_PATH and DB_URL before starting.

    cmd: migrate -path {{.MIGRATIONS_PATH}} -database "{{.DB_URL}}" up
    requires:
      vars: [ MIGRATIONS_PATH, DB_URL ]

  migrate-down:
    desc: "Reverts the last applied migration."

    summary: |
      Reverts the last applied migration.

      Please make sure you have set MIGRATIONS_PATH and DB_URL before starting.

    cmd: migrate -path {{.MIGRATIONS_PATH}} -database "{{.DB_URL}}" down 1
    requires:
      vars: [ MIGRATIONS_PATH, DB_URL ]

  migrate-down-all:
    desc: "Reverts all migrations."
    summary: |
      Reverts all applied migration.
      
      Please make sure you have set MIGRATIONS_PATH and DB_URL before starting.

    cmd: migrate -path {{.MIGRATIONS_PATH}} -database "{{.DB_URL}}" down
    requires:
      vars: [ MIGRATIONS_PATH, DB_URL ]

  migrate-create:
    desc: "Creates a new up/down migration file with specific name."
    summary: |
      Creates a new up/down migration file with specific name.
      
      Please make sure you have set MIGRATIONS_PATH and NAME before starting.

    cmd: migrate create -ext sql -dir {{.MIGRATIONS_PATH}} -seq {{.NAME}}
    requires:
      vars: [ MIGRATIONS_PATH, NAME ]

  migrate-force:
    desc: "Forces the database version to a specific version."
    summary: |
      Forces the database version to a specific version.
      
      Please make sure you have set MIGRATIONS_PATH, DB_URL and VERSION before starting.

    cmd: migrate -path {{.MIGRATIONS_PATH}} -database "{{.DB_URL}}" force {{.VERSION}}
    requires:
      vars: [ MIGRATIONS_PATH, VERSION ]

  run-api:
    desc: "Starts the API"
    cmds:
      - go build -o bin/api ./cmd/api
      - ./bin/http

  mockgen:
    desc: "Generates mock implementation from specific file."
    summary: |
      Generates mock implementation from specific file.
      
      Please make sure you have set FILE before starting.

    cmd: mockgen -source=internal/core/port/{{.FILE}}.go -destination=internal/core/port/mock/{{.FILE}}.go -package=mock -typed=true
    requires:
      vars: [ FILE ]