// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/image.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/image.go -destination=internal/core/port/mock/image.go -package=mock -typed=true
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockImageRepository is a mock of ImageRepository interface.
type MockImageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockImageRepositoryMockRecorder
	isgomock struct{}
}

// MockImageRepositoryMockRecorder is the mock recorder for MockImageRepository.
type MockImageRepositoryMockRecorder struct {
	mock *MockImageRepository
}

// NewMockImageRepository creates a new mock instance.
func NewMockImageRepository(ctrl *gomock.Controller) *MockImageRepository {
	mock := &MockImageRepository{ctrl: ctrl}
	mock.recorder = &MockImageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageRepository) EXPECT() *MockImageRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockImageRepository) Save(ctx context.Context, image io.Reader, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, image, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockImageRepositoryMockRecorder) Save(ctx, image, id any) *MockImageRepositorySaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockImageRepository)(nil).Save), ctx, image, id)
	return &MockImageRepositorySaveCall{Call: call}
}

// MockImageRepositorySaveCall wrap *gomock.Call
type MockImageRepositorySaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImageRepositorySaveCall) Return(arg0 string, arg1 error) *MockImageRepositorySaveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImageRepositorySaveCall) Do(f func(context.Context, io.Reader, uuid.UUID) (string, error)) *MockImageRepositorySaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImageRepositorySaveCall) DoAndReturn(f func(context.Context, io.Reader, uuid.UUID) (string, error)) *MockImageRepositorySaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
