// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/image.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/image.go -destination=internal/core/port/mock/image.go -package=mock -typed=true
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"
	domain "restaurant/internal/core/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockImageRepository is a mock of ImageRepository interface.
type MockImageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockImageRepositoryMockRecorder
	isgomock struct{}
}

// MockImageRepositoryMockRecorder is the mock recorder for MockImageRepository.
type MockImageRepositoryMockRecorder struct {
	mock *MockImageRepository
}

// NewMockImageRepository creates a new mock instance.
func NewMockImageRepository(ctrl *gomock.Controller) *MockImageRepository {
	mock := &MockImageRepository{ctrl: ctrl}
	mock.recorder = &MockImageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageRepository) EXPECT() *MockImageRepositoryMockRecorder {
	return m.recorder
}

// DeleteImage mocks base method.
func (m *MockImageRepository) DeleteImage(ctx context.Context, deleteUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, deleteUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockImageRepositoryMockRecorder) DeleteImage(ctx, deleteUrl any) *MockImageRepositoryDeleteImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockImageRepository)(nil).DeleteImage), ctx, deleteUrl)
	return &MockImageRepositoryDeleteImageCall{Call: call}
}

// MockImageRepositoryDeleteImageCall wrap *gomock.Call
type MockImageRepositoryDeleteImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImageRepositoryDeleteImageCall) Return(arg0 error) *MockImageRepositoryDeleteImageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImageRepositoryDeleteImageCall) Do(f func(context.Context, string) error) *MockImageRepositoryDeleteImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImageRepositoryDeleteImageCall) DoAndReturn(f func(context.Context, string) error) *MockImageRepositoryDeleteImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveImage mocks base method.
func (m *MockImageRepository) SaveImage(ctx context.Context, data io.Reader) (*domain.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveImage", ctx, data)
	ret0, _ := ret[0].(*domain.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveImage indicates an expected call of SaveImage.
func (mr *MockImageRepositoryMockRecorder) SaveImage(ctx, data any) *MockImageRepositorySaveImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveImage", reflect.TypeOf((*MockImageRepository)(nil).SaveImage), ctx, data)
	return &MockImageRepositorySaveImageCall{Call: call}
}

// MockImageRepositorySaveImageCall wrap *gomock.Call
type MockImageRepositorySaveImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImageRepositorySaveImageCall) Return(arg0 *domain.Image, arg1 error) *MockImageRepositorySaveImageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImageRepositorySaveImageCall) Do(f func(context.Context, io.Reader) (*domain.Image, error)) *MockImageRepositorySaveImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImageRepositorySaveImageCall) DoAndReturn(f func(context.Context, io.Reader) (*domain.Image, error)) *MockImageRepositorySaveImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
