// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/order.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/order.go -destination=internal/core/port/mock/order.go -package=mock -typed=true
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	domain "restaurant/internal/core/domain"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// AddOrderedProduct mocks base method.
func (m *MockOrderRepository) AddOrderedProduct(ctx context.Context, product *domain.OrderedProduct) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrderedProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrderedProduct indicates an expected call of AddOrderedProduct.
func (mr *MockOrderRepositoryMockRecorder) AddOrderedProduct(ctx, product any) *MockOrderRepositoryAddOrderedProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrderedProduct", reflect.TypeOf((*MockOrderRepository)(nil).AddOrderedProduct), ctx, product)
	return &MockOrderRepositoryAddOrderedProductCall{Call: call}
}

// MockOrderRepositoryAddOrderedProductCall wrap *gomock.Call
type MockOrderRepositoryAddOrderedProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryAddOrderedProductCall) Return(arg0 error) *MockOrderRepositoryAddOrderedProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryAddOrderedProductCall) Do(f func(context.Context, *domain.OrderedProduct) error) *MockOrderRepositoryAddOrderedProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryAddOrderedProductCall) DoAndReturn(f func(context.Context, *domain.OrderedProduct) error) *MockOrderRepositoryAddOrderedProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddSession mocks base method.
func (m *MockOrderRepository) AddSession(ctx context.Context, session *domain.OrderSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSession indicates an expected call of AddSession.
func (mr *MockOrderRepositoryMockRecorder) AddSession(ctx, session any) *MockOrderRepositoryAddSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockOrderRepository)(nil).AddSession), ctx, session)
	return &MockOrderRepositoryAddSessionCall{Call: call}
}

// MockOrderRepositoryAddSessionCall wrap *gomock.Call
type MockOrderRepositoryAddSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryAddSessionCall) Return(arg0 error) *MockOrderRepositoryAddSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryAddSessionCall) Do(f func(context.Context, *domain.OrderSession) error) *MockOrderRepositoryAddSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryAddSessionCall) DoAndReturn(f func(context.Context, *domain.OrderSession) error) *MockOrderRepositoryAddSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteOrderedProduct mocks base method.
func (m *MockOrderRepository) DeleteOrderedProduct(ctx context.Context, orderedProductId uuid.UUID) (*domain.OrderedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderedProduct", ctx, orderedProductId)
	ret0, _ := ret[0].(*domain.OrderedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrderedProduct indicates an expected call of DeleteOrderedProduct.
func (mr *MockOrderRepositoryMockRecorder) DeleteOrderedProduct(ctx, orderedProductId any) *MockOrderRepositoryDeleteOrderedProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderedProduct", reflect.TypeOf((*MockOrderRepository)(nil).DeleteOrderedProduct), ctx, orderedProductId)
	return &MockOrderRepositoryDeleteOrderedProductCall{Call: call}
}

// MockOrderRepositoryDeleteOrderedProductCall wrap *gomock.Call
type MockOrderRepositoryDeleteOrderedProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryDeleteOrderedProductCall) Return(arg0 *domain.OrderedProduct, arg1 error) *MockOrderRepositoryDeleteOrderedProductCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryDeleteOrderedProductCall) Do(f func(context.Context, uuid.UUID) (*domain.OrderedProduct, error)) *MockOrderRepositoryDeleteOrderedProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryDeleteOrderedProductCall) DoAndReturn(f func(context.Context, uuid.UUID) (*domain.OrderedProduct, error)) *MockOrderRepositoryDeleteOrderedProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteOrderedProductsBySessionId mocks base method.
func (m *MockOrderRepository) DeleteOrderedProductsBySessionId(ctx context.Context, sessionId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderedProductsBySessionId", ctx, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderedProductsBySessionId indicates an expected call of DeleteOrderedProductsBySessionId.
func (mr *MockOrderRepositoryMockRecorder) DeleteOrderedProductsBySessionId(ctx, sessionId any) *MockOrderRepositoryDeleteOrderedProductsBySessionIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderedProductsBySessionId", reflect.TypeOf((*MockOrderRepository)(nil).DeleteOrderedProductsBySessionId), ctx, sessionId)
	return &MockOrderRepositoryDeleteOrderedProductsBySessionIdCall{Call: call}
}

// MockOrderRepositoryDeleteOrderedProductsBySessionIdCall wrap *gomock.Call
type MockOrderRepositoryDeleteOrderedProductsBySessionIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryDeleteOrderedProductsBySessionIdCall) Return(arg0 error) *MockOrderRepositoryDeleteOrderedProductsBySessionIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryDeleteOrderedProductsBySessionIdCall) Do(f func(context.Context, uuid.UUID) error) *MockOrderRepositoryDeleteOrderedProductsBySessionIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryDeleteOrderedProductsBySessionIdCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockOrderRepositoryDeleteOrderedProductsBySessionIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeletePendingOrderedProduct mocks base method.
func (m *MockOrderRepository) DeletePendingOrderedProduct(ctx context.Context, orderedProductId uuid.UUID) (*domain.OrderedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingOrderedProduct", ctx, orderedProductId)
	ret0, _ := ret[0].(*domain.OrderedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePendingOrderedProduct indicates an expected call of DeletePendingOrderedProduct.
func (mr *MockOrderRepositoryMockRecorder) DeletePendingOrderedProduct(ctx, orderedProductId any) *MockOrderRepositoryDeletePendingOrderedProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingOrderedProduct", reflect.TypeOf((*MockOrderRepository)(nil).DeletePendingOrderedProduct), ctx, orderedProductId)
	return &MockOrderRepositoryDeletePendingOrderedProductCall{Call: call}
}

// MockOrderRepositoryDeletePendingOrderedProductCall wrap *gomock.Call
type MockOrderRepositoryDeletePendingOrderedProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryDeletePendingOrderedProductCall) Return(arg0 *domain.OrderedProduct, arg1 error) *MockOrderRepositoryDeletePendingOrderedProductCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryDeletePendingOrderedProductCall) Do(f func(context.Context, uuid.UUID) (*domain.OrderedProduct, error)) *MockOrderRepositoryDeletePendingOrderedProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryDeletePendingOrderedProductCall) DoAndReturn(f func(context.Context, uuid.UUID) (*domain.OrderedProduct, error)) *MockOrderRepositoryDeletePendingOrderedProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSession mocks base method.
func (m *MockOrderRepository) DeleteSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockOrderRepositoryMockRecorder) DeleteSession(ctx, id any) *MockOrderRepositoryDeleteSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockOrderRepository)(nil).DeleteSession), ctx, id)
	return &MockOrderRepositoryDeleteSessionCall{Call: call}
}

// MockOrderRepositoryDeleteSessionCall wrap *gomock.Call
type MockOrderRepositoryDeleteSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryDeleteSessionCall) Return(arg0 error) *MockOrderRepositoryDeleteSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryDeleteSessionCall) Do(f func(context.Context, uuid.UUID) error) *MockOrderRepositoryDeleteSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryDeleteSessionCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockOrderRepositoryDeleteSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBillFromSession mocks base method.
func (m *MockOrderRepository) GetBillFromSession(ctx context.Context, id uuid.UUID) (*domain.Bill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBillFromSession", ctx, id)
	ret0, _ := ret[0].(*domain.Bill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBillFromSession indicates an expected call of GetBillFromSession.
func (mr *MockOrderRepositoryMockRecorder) GetBillFromSession(ctx, id any) *MockOrderRepositoryGetBillFromSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBillFromSession", reflect.TypeOf((*MockOrderRepository)(nil).GetBillFromSession), ctx, id)
	return &MockOrderRepositoryGetBillFromSessionCall{Call: call}
}

// MockOrderRepositoryGetBillFromSessionCall wrap *gomock.Call
type MockOrderRepositoryGetBillFromSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetBillFromSessionCall) Return(arg0 *domain.Bill, arg1 error) *MockOrderRepositoryGetBillFromSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetBillFromSessionCall) Do(f func(context.Context, uuid.UUID) (*domain.Bill, error)) *MockOrderRepositoryGetBillFromSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetBillFromSessionCall) DoAndReturn(f func(context.Context, uuid.UUID) (*domain.Bill, error)) *MockOrderRepositoryGetBillFromSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrderedProducts mocks base method.
func (m *MockOrderRepository) GetOrderedProducts(ctx context.Context) ([]domain.OrderedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderedProducts", ctx)
	ret0, _ := ret[0].([]domain.OrderedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderedProducts indicates an expected call of GetOrderedProducts.
func (mr *MockOrderRepositoryMockRecorder) GetOrderedProducts(ctx any) *MockOrderRepositoryGetOrderedProductsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderedProducts", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderedProducts), ctx)
	return &MockOrderRepositoryGetOrderedProductsCall{Call: call}
}

// MockOrderRepositoryGetOrderedProductsCall wrap *gomock.Call
type MockOrderRepositoryGetOrderedProductsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetOrderedProductsCall) Return(arg0 []domain.OrderedProduct, arg1 error) *MockOrderRepositoryGetOrderedProductsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetOrderedProductsCall) Do(f func(context.Context) ([]domain.OrderedProduct, error)) *MockOrderRepositoryGetOrderedProductsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetOrderedProductsCall) DoAndReturn(f func(context.Context) ([]domain.OrderedProduct, error)) *MockOrderRepositoryGetOrderedProductsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSessionByID mocks base method.
func (m *MockOrderRepository) GetSessionByID(ctx context.Context, id uuid.UUID) (*domain.OrderSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, id)
	ret0, _ := ret[0].(*domain.OrderSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockOrderRepositoryMockRecorder) GetSessionByID(ctx, id any) *MockOrderRepositoryGetSessionByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockOrderRepository)(nil).GetSessionByID), ctx, id)
	return &MockOrderRepositoryGetSessionByIDCall{Call: call}
}

// MockOrderRepositoryGetSessionByIDCall wrap *gomock.Call
type MockOrderRepositoryGetSessionByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetSessionByIDCall) Return(arg0 *domain.OrderSession, arg1 error) *MockOrderRepositoryGetSessionByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetSessionByIDCall) Do(f func(context.Context, uuid.UUID) (*domain.OrderSession, error)) *MockOrderRepositoryGetSessionByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetSessionByIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (*domain.OrderSession, error)) *MockOrderRepositoryGetSessionByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSessions mocks base method.
func (m *MockOrderRepository) GetSessions(ctx context.Context) ([]domain.OrderSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessions", ctx)
	ret0, _ := ret[0].([]domain.OrderSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessions indicates an expected call of GetSessions.
func (mr *MockOrderRepositoryMockRecorder) GetSessions(ctx any) *MockOrderRepositoryGetSessionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessions", reflect.TypeOf((*MockOrderRepository)(nil).GetSessions), ctx)
	return &MockOrderRepositoryGetSessionsCall{Call: call}
}

// MockOrderRepositoryGetSessionsCall wrap *gomock.Call
type MockOrderRepositoryGetSessionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryGetSessionsCall) Return(arg0 []domain.OrderSession, arg1 error) *MockOrderRepositoryGetSessionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryGetSessionsCall) Do(f func(context.Context) ([]domain.OrderSession, error)) *MockOrderRepositoryGetSessionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryGetSessionsCall) DoAndReturn(f func(context.Context) ([]domain.OrderSession, error)) *MockOrderRepositoryGetSessionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasIncompletedOrderedProducts mocks base method.
func (m *MockOrderRepository) HasIncompletedOrderedProducts(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasIncompletedOrderedProducts", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasIncompletedOrderedProducts indicates an expected call of HasIncompletedOrderedProducts.
func (mr *MockOrderRepositoryMockRecorder) HasIncompletedOrderedProducts(ctx, id any) *MockOrderRepositoryHasIncompletedOrderedProductsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasIncompletedOrderedProducts", reflect.TypeOf((*MockOrderRepository)(nil).HasIncompletedOrderedProducts), ctx, id)
	return &MockOrderRepositoryHasIncompletedOrderedProductsCall{Call: call}
}

// MockOrderRepositoryHasIncompletedOrderedProductsCall wrap *gomock.Call
type MockOrderRepositoryHasIncompletedOrderedProductsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryHasIncompletedOrderedProductsCall) Return(arg0 bool, arg1 error) *MockOrderRepositoryHasIncompletedOrderedProductsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryHasIncompletedOrderedProductsCall) Do(f func(context.Context, uuid.UUID) (bool, error)) *MockOrderRepositoryHasIncompletedOrderedProductsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryHasIncompletedOrderedProductsCall) DoAndReturn(f func(context.Context, uuid.UUID) (bool, error)) *MockOrderRepositoryHasIncompletedOrderedProductsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateOrderedProductStatus mocks base method.
func (m *MockOrderRepository) UpdateOrderedProductStatus(ctx context.Context, id uuid.UUID, status domain.OrderedProductStatus) (*domain.OrderedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderedProductStatus", ctx, id, status)
	ret0, _ := ret[0].(*domain.OrderedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderedProductStatus indicates an expected call of UpdateOrderedProductStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrderedProductStatus(ctx, id, status any) *MockOrderRepositoryUpdateOrderedProductStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderedProductStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrderedProductStatus), ctx, id, status)
	return &MockOrderRepositoryUpdateOrderedProductStatusCall{Call: call}
}

// MockOrderRepositoryUpdateOrderedProductStatusCall wrap *gomock.Call
type MockOrderRepositoryUpdateOrderedProductStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryUpdateOrderedProductStatusCall) Return(arg0 *domain.OrderedProduct, arg1 error) *MockOrderRepositoryUpdateOrderedProductStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryUpdateOrderedProductStatusCall) Do(f func(context.Context, uuid.UUID, domain.OrderedProductStatus) (*domain.OrderedProduct, error)) *MockOrderRepositoryUpdateOrderedProductStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryUpdateOrderedProductStatusCall) DoAndReturn(f func(context.Context, uuid.UUID, domain.OrderedProductStatus) (*domain.OrderedProduct, error)) *MockOrderRepositoryUpdateOrderedProductStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateSession mocks base method.
func (m *MockOrderRepository) UpdateSession(ctx context.Context, session *domain.UpdateOrderSessionDTO) (*domain.OrderSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(*domain.OrderSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockOrderRepositoryMockRecorder) UpdateSession(ctx, session any) *MockOrderRepositoryUpdateSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockOrderRepository)(nil).UpdateSession), ctx, session)
	return &MockOrderRepositoryUpdateSessionCall{Call: call}
}

// MockOrderRepositoryUpdateSessionCall wrap *gomock.Call
type MockOrderRepositoryUpdateSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderRepositoryUpdateSessionCall) Return(arg0 *domain.OrderSession, arg1 error) *MockOrderRepositoryUpdateSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderRepositoryUpdateSessionCall) Do(f func(context.Context, *domain.UpdateOrderSessionDTO) (*domain.OrderSession, error)) *MockOrderRepositoryUpdateSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderRepositoryUpdateSessionCall) DoAndReturn(f func(context.Context, *domain.UpdateOrderSessionDTO) (*domain.OrderSession, error)) *MockOrderRepositoryUpdateSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockOrderService) CreateSession(ctx context.Context) (*domain.OrderSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx)
	ret0, _ := ret[0].(*domain.OrderSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockOrderServiceMockRecorder) CreateSession(ctx any) *MockOrderServiceCreateSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockOrderService)(nil).CreateSession), ctx)
	return &MockOrderServiceCreateSessionCall{Call: call}
}

// MockOrderServiceCreateSessionCall wrap *gomock.Call
type MockOrderServiceCreateSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceCreateSessionCall) Return(arg0 *domain.OrderSession, arg1 error) *MockOrderServiceCreateSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceCreateSessionCall) Do(f func(context.Context) (*domain.OrderSession, error)) *MockOrderServiceCreateSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceCreateSessionCall) DoAndReturn(f func(context.Context) (*domain.OrderSession, error)) *MockOrderServiceCreateSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteOrderedProduct mocks base method.
func (m *MockOrderService) DeleteOrderedProduct(ctx context.Context, productId uuid.UUID, isPrivilegedCall bool) (*domain.OrderedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderedProduct", ctx, productId, isPrivilegedCall)
	ret0, _ := ret[0].(*domain.OrderedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrderedProduct indicates an expected call of DeleteOrderedProduct.
func (mr *MockOrderServiceMockRecorder) DeleteOrderedProduct(ctx, productId, isPrivilegedCall any) *MockOrderServiceDeleteOrderedProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderedProduct", reflect.TypeOf((*MockOrderService)(nil).DeleteOrderedProduct), ctx, productId, isPrivilegedCall)
	return &MockOrderServiceDeleteOrderedProductCall{Call: call}
}

// MockOrderServiceDeleteOrderedProductCall wrap *gomock.Call
type MockOrderServiceDeleteOrderedProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceDeleteOrderedProductCall) Return(arg0 *domain.OrderedProduct, arg1 error) *MockOrderServiceDeleteOrderedProductCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceDeleteOrderedProductCall) Do(f func(context.Context, uuid.UUID, bool) (*domain.OrderedProduct, error)) *MockOrderServiceDeleteOrderedProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceDeleteOrderedProductCall) DoAndReturn(f func(context.Context, uuid.UUID, bool) (*domain.OrderedProduct, error)) *MockOrderServiceDeleteOrderedProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSession mocks base method.
func (m *MockOrderService) DeleteSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockOrderServiceMockRecorder) DeleteSession(ctx, id any) *MockOrderServiceDeleteSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockOrderService)(nil).DeleteSession), ctx, id)
	return &MockOrderServiceDeleteSessionCall{Call: call}
}

// MockOrderServiceDeleteSessionCall wrap *gomock.Call
type MockOrderServiceDeleteSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceDeleteSessionCall) Return(arg0 error) *MockOrderServiceDeleteSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceDeleteSessionCall) Do(f func(context.Context, uuid.UUID) error) *MockOrderServiceDeleteSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceDeleteSessionCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockOrderServiceDeleteSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBill mocks base method.
func (m *MockOrderService) GetBill(ctx context.Context, sessionId uuid.UUID) (*domain.Bill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBill", ctx, sessionId)
	ret0, _ := ret[0].(*domain.Bill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBill indicates an expected call of GetBill.
func (mr *MockOrderServiceMockRecorder) GetBill(ctx, sessionId any) *MockOrderServiceGetBillCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBill", reflect.TypeOf((*MockOrderService)(nil).GetBill), ctx, sessionId)
	return &MockOrderServiceGetBillCall{Call: call}
}

// MockOrderServiceGetBillCall wrap *gomock.Call
type MockOrderServiceGetBillCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceGetBillCall) Return(arg0 *domain.Bill, arg1 error) *MockOrderServiceGetBillCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceGetBillCall) Do(f func(context.Context, uuid.UUID) (*domain.Bill, error)) *MockOrderServiceGetBillCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceGetBillCall) DoAndReturn(f func(context.Context, uuid.UUID) (*domain.Bill, error)) *MockOrderServiceGetBillCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrderedProducts mocks base method.
func (m *MockOrderService) GetOrderedProducts(ctx context.Context) ([]domain.OrderedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderedProducts", ctx)
	ret0, _ := ret[0].([]domain.OrderedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderedProducts indicates an expected call of GetOrderedProducts.
func (mr *MockOrderServiceMockRecorder) GetOrderedProducts(ctx any) *MockOrderServiceGetOrderedProductsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderedProducts", reflect.TypeOf((*MockOrderService)(nil).GetOrderedProducts), ctx)
	return &MockOrderServiceGetOrderedProductsCall{Call: call}
}

// MockOrderServiceGetOrderedProductsCall wrap *gomock.Call
type MockOrderServiceGetOrderedProductsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceGetOrderedProductsCall) Return(arg0 []domain.OrderedProduct, arg1 error) *MockOrderServiceGetOrderedProductsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceGetOrderedProductsCall) Do(f func(context.Context) ([]domain.OrderedProduct, error)) *MockOrderServiceGetOrderedProductsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceGetOrderedProductsCall) DoAndReturn(f func(context.Context) ([]domain.OrderedProduct, error)) *MockOrderServiceGetOrderedProductsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSessions mocks base method.
func (m *MockOrderService) GetSessions(ctx context.Context) ([]domain.OrderSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessions", ctx)
	ret0, _ := ret[0].([]domain.OrderSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessions indicates an expected call of GetSessions.
func (mr *MockOrderServiceMockRecorder) GetSessions(ctx any) *MockOrderServiceGetSessionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessions", reflect.TypeOf((*MockOrderService)(nil).GetSessions), ctx)
	return &MockOrderServiceGetSessionsCall{Call: call}
}

// MockOrderServiceGetSessionsCall wrap *gomock.Call
type MockOrderServiceGetSessionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceGetSessionsCall) Return(arg0 []domain.OrderSession, arg1 error) *MockOrderServiceGetSessionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceGetSessionsCall) Do(f func(context.Context) ([]domain.OrderSession, error)) *MockOrderServiceGetSessionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceGetSessionsCall) DoAndReturn(f func(context.Context) ([]domain.OrderSession, error)) *MockOrderServiceGetSessionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OrderProduct mocks base method.
func (m *MockOrderService) OrderProduct(ctx context.Context, productId, sessionId uuid.UUID) (*domain.OrderedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderProduct", ctx, productId, sessionId)
	ret0, _ := ret[0].(*domain.OrderedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderProduct indicates an expected call of OrderProduct.
func (mr *MockOrderServiceMockRecorder) OrderProduct(ctx, productId, sessionId any) *MockOrderServiceOrderProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderProduct", reflect.TypeOf((*MockOrderService)(nil).OrderProduct), ctx, productId, sessionId)
	return &MockOrderServiceOrderProductCall{Call: call}
}

// MockOrderServiceOrderProductCall wrap *gomock.Call
type MockOrderServiceOrderProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceOrderProductCall) Return(arg0 *domain.OrderedProduct, arg1 error) *MockOrderServiceOrderProductCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceOrderProductCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) (*domain.OrderedProduct, error)) *MockOrderServiceOrderProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceOrderProductCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) (*domain.OrderedProduct, error)) *MockOrderServiceOrderProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PayBill mocks base method.
func (m *MockOrderService) PayBill(ctx context.Context, sessionId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayBill", ctx, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PayBill indicates an expected call of PayBill.
func (mr *MockOrderServiceMockRecorder) PayBill(ctx, sessionId any) *MockOrderServicePayBillCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayBill", reflect.TypeOf((*MockOrderService)(nil).PayBill), ctx, sessionId)
	return &MockOrderServicePayBillCall{Call: call}
}

// MockOrderServicePayBillCall wrap *gomock.Call
type MockOrderServicePayBillCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServicePayBillCall) Return(arg0 error) *MockOrderServicePayBillCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServicePayBillCall) Do(f func(context.Context, uuid.UUID) error) *MockOrderServicePayBillCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServicePayBillCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockOrderServicePayBillCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateOrderedProductStatus mocks base method.
func (m *MockOrderService) UpdateOrderedProductStatus(ctx context.Context, id uuid.UUID, status domain.OrderedProductStatus) (*domain.OrderedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderedProductStatus", ctx, id, status)
	ret0, _ := ret[0].(*domain.OrderedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderedProductStatus indicates an expected call of UpdateOrderedProductStatus.
func (mr *MockOrderServiceMockRecorder) UpdateOrderedProductStatus(ctx, id, status any) *MockOrderServiceUpdateOrderedProductStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderedProductStatus", reflect.TypeOf((*MockOrderService)(nil).UpdateOrderedProductStatus), ctx, id, status)
	return &MockOrderServiceUpdateOrderedProductStatusCall{Call: call}
}

// MockOrderServiceUpdateOrderedProductStatusCall wrap *gomock.Call
type MockOrderServiceUpdateOrderedProductStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceUpdateOrderedProductStatusCall) Return(arg0 *domain.OrderedProduct, arg1 error) *MockOrderServiceUpdateOrderedProductStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceUpdateOrderedProductStatusCall) Do(f func(context.Context, uuid.UUID, domain.OrderedProductStatus) (*domain.OrderedProduct, error)) *MockOrderServiceUpdateOrderedProductStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceUpdateOrderedProductStatusCall) DoAndReturn(f func(context.Context, uuid.UUID, domain.OrderedProductStatus) (*domain.OrderedProduct, error)) *MockOrderServiceUpdateOrderedProductStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateSession mocks base method.
func (m *MockOrderService) UpdateSession(ctx context.Context, session *domain.UpdateOrderSessionDTO) (*domain.OrderSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(*domain.OrderSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockOrderServiceMockRecorder) UpdateSession(ctx, session any) *MockOrderServiceUpdateSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockOrderService)(nil).UpdateSession), ctx, session)
	return &MockOrderServiceUpdateSessionCall{Call: call}
}

// MockOrderServiceUpdateSessionCall wrap *gomock.Call
type MockOrderServiceUpdateSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceUpdateSessionCall) Return(arg0 *domain.OrderSession, arg1 error) *MockOrderServiceUpdateSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceUpdateSessionCall) Do(f func(context.Context, *domain.UpdateOrderSessionDTO) (*domain.OrderSession, error)) *MockOrderServiceUpdateSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceUpdateSessionCall) DoAndReturn(f func(context.Context, *domain.UpdateOrderSessionDTO) (*domain.OrderSession, error)) *MockOrderServiceUpdateSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidateSession mocks base method.
func (m *MockOrderService) ValidateSession(ctx context.Context, sessionId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockOrderServiceMockRecorder) ValidateSession(ctx, sessionId any) *MockOrderServiceValidateSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockOrderService)(nil).ValidateSession), ctx, sessionId)
	return &MockOrderServiceValidateSessionCall{Call: call}
}

// MockOrderServiceValidateSessionCall wrap *gomock.Call
type MockOrderServiceValidateSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderServiceValidateSessionCall) Return(arg0 error) *MockOrderServiceValidateSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderServiceValidateSessionCall) Do(f func(context.Context, uuid.UUID) error) *MockOrderServiceValidateSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderServiceValidateSessionCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockOrderServiceValidateSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
