// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/product.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/product.go -destination=internal/core/port/mock/product.go -package=mock -typed=true
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"
	domain "restaurant/internal/core/domain"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// AddCategory mocks base method.
func (m *MockProductRepository) AddCategory(ctx context.Context, category *domain.ProductCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCategory", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCategory indicates an expected call of AddCategory.
func (mr *MockProductRepositoryMockRecorder) AddCategory(ctx, category any) *MockProductRepositoryAddCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCategory", reflect.TypeOf((*MockProductRepository)(nil).AddCategory), ctx, category)
	return &MockProductRepositoryAddCategoryCall{Call: call}
}

// MockProductRepositoryAddCategoryCall wrap *gomock.Call
type MockProductRepositoryAddCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryAddCategoryCall) Return(arg0 error) *MockProductRepositoryAddCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryAddCategoryCall) Do(f func(context.Context, *domain.ProductCategory) error) *MockProductRepositoryAddCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryAddCategoryCall) DoAndReturn(f func(context.Context, *domain.ProductCategory) error) *MockProductRepositoryAddCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddProduct mocks base method.
func (m *MockProductRepository) AddProduct(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockProductRepositoryMockRecorder) AddProduct(ctx, product any) *MockProductRepositoryAddProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductRepository)(nil).AddProduct), ctx, product)
	return &MockProductRepositoryAddProductCall{Call: call}
}

// MockProductRepositoryAddProductCall wrap *gomock.Call
type MockProductRepositoryAddProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryAddProductCall) Return(arg0 error) *MockProductRepositoryAddProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryAddProductCall) Do(f func(context.Context, *domain.Product) error) *MockProductRepositoryAddProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryAddProductCall) DoAndReturn(f func(context.Context, *domain.Product) error) *MockProductRepositoryAddProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteCategory mocks base method.
func (m *MockProductRepository) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockProductRepositoryMockRecorder) DeleteCategory(ctx, id any) *MockProductRepositoryDeleteCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockProductRepository)(nil).DeleteCategory), ctx, id)
	return &MockProductRepositoryDeleteCategoryCall{Call: call}
}

// MockProductRepositoryDeleteCategoryCall wrap *gomock.Call
type MockProductRepositoryDeleteCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryDeleteCategoryCall) Return(arg0 error) *MockProductRepositoryDeleteCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryDeleteCategoryCall) Do(f func(context.Context, uuid.UUID) error) *MockProductRepositoryDeleteCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryDeleteCategoryCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockProductRepositoryDeleteCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProductById mocks base method.
func (m *MockProductRepository) DeleteProductById(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductById", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProductById indicates an expected call of DeleteProductById.
func (mr *MockProductRepositoryMockRecorder) DeleteProductById(ctx, id any) *MockProductRepositoryDeleteProductByIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductById", reflect.TypeOf((*MockProductRepository)(nil).DeleteProductById), ctx, id)
	return &MockProductRepositoryDeleteProductByIdCall{Call: call}
}

// MockProductRepositoryDeleteProductByIdCall wrap *gomock.Call
type MockProductRepositoryDeleteProductByIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryDeleteProductByIdCall) Return(arg0 *domain.Product, arg1 error) *MockProductRepositoryDeleteProductByIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryDeleteProductByIdCall) Do(f func(context.Context, uuid.UUID) (*domain.Product, error)) *MockProductRepositoryDeleteProductByIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryDeleteProductByIdCall) DoAndReturn(f func(context.Context, uuid.UUID) (*domain.Product, error)) *MockProductRepositoryDeleteProductByIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProductsByCategory mocks base method.
func (m *MockProductRepository) DeleteProductsByCategory(ctx context.Context, categoryId uuid.UUID) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductsByCategory", ctx, categoryId)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProductsByCategory indicates an expected call of DeleteProductsByCategory.
func (mr *MockProductRepositoryMockRecorder) DeleteProductsByCategory(ctx, categoryId any) *MockProductRepositoryDeleteProductsByCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductsByCategory", reflect.TypeOf((*MockProductRepository)(nil).DeleteProductsByCategory), ctx, categoryId)
	return &MockProductRepositoryDeleteProductsByCategoryCall{Call: call}
}

// MockProductRepositoryDeleteProductsByCategoryCall wrap *gomock.Call
type MockProductRepositoryDeleteProductsByCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryDeleteProductsByCategoryCall) Return(arg0 []domain.Product, arg1 error) *MockProductRepositoryDeleteProductsByCategoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryDeleteProductsByCategoryCall) Do(f func(context.Context, uuid.UUID) ([]domain.Product, error)) *MockProductRepositoryDeleteProductsByCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryDeleteProductsByCategoryCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]domain.Product, error)) *MockProductRepositoryDeleteProductsByCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProductById mocks base method.
func (m *MockProductRepository) GetProductById(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductById", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductById indicates an expected call of GetProductById.
func (mr *MockProductRepositoryMockRecorder) GetProductById(ctx, id any) *MockProductRepositoryGetProductByIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductById", reflect.TypeOf((*MockProductRepository)(nil).GetProductById), ctx, id)
	return &MockProductRepositoryGetProductByIdCall{Call: call}
}

// MockProductRepositoryGetProductByIdCall wrap *gomock.Call
type MockProductRepositoryGetProductByIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryGetProductByIdCall) Return(arg0 *domain.Product, arg1 error) *MockProductRepositoryGetProductByIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryGetProductByIdCall) Do(f func(context.Context, uuid.UUID) (*domain.Product, error)) *MockProductRepositoryGetProductByIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryGetProductByIdCall) DoAndReturn(f func(context.Context, uuid.UUID) (*domain.Product, error)) *MockProductRepositoryGetProductByIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProductCategories mocks base method.
func (m *MockProductRepository) GetProductCategories(ctx context.Context) ([]domain.ProductCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductCategories", ctx)
	ret0, _ := ret[0].([]domain.ProductCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductCategories indicates an expected call of GetProductCategories.
func (mr *MockProductRepositoryMockRecorder) GetProductCategories(ctx any) *MockProductRepositoryGetProductCategoriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductCategories", reflect.TypeOf((*MockProductRepository)(nil).GetProductCategories), ctx)
	return &MockProductRepositoryGetProductCategoriesCall{Call: call}
}

// MockProductRepositoryGetProductCategoriesCall wrap *gomock.Call
type MockProductRepositoryGetProductCategoriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryGetProductCategoriesCall) Return(arg0 []domain.ProductCategory, arg1 error) *MockProductRepositoryGetProductCategoriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryGetProductCategoriesCall) Do(f func(context.Context) ([]domain.ProductCategory, error)) *MockProductRepositoryGetProductCategoriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryGetProductCategoriesCall) DoAndReturn(f func(context.Context) ([]domain.ProductCategory, error)) *MockProductRepositoryGetProductCategoriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProducts mocks base method.
func (m *MockProductRepository) GetProducts(ctx context.Context) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", ctx)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockProductRepositoryMockRecorder) GetProducts(ctx any) *MockProductRepositoryGetProductsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockProductRepository)(nil).GetProducts), ctx)
	return &MockProductRepositoryGetProductsCall{Call: call}
}

// MockProductRepositoryGetProductsCall wrap *gomock.Call
type MockProductRepositoryGetProductsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryGetProductsCall) Return(arg0 []domain.Product, arg1 error) *MockProductRepositoryGetProductsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryGetProductsCall) Do(f func(context.Context) ([]domain.Product, error)) *MockProductRepositoryGetProductsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryGetProductsCall) DoAndReturn(f func(context.Context) ([]domain.Product, error)) *MockProductRepositoryGetProductsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProductsByCategory mocks base method.
func (m *MockProductRepository) GetProductsByCategory(ctx context.Context, categoryId uuid.UUID) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByCategory", ctx, categoryId)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByCategory indicates an expected call of GetProductsByCategory.
func (mr *MockProductRepositoryMockRecorder) GetProductsByCategory(ctx, categoryId any) *MockProductRepositoryGetProductsByCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByCategory", reflect.TypeOf((*MockProductRepository)(nil).GetProductsByCategory), ctx, categoryId)
	return &MockProductRepositoryGetProductsByCategoryCall{Call: call}
}

// MockProductRepositoryGetProductsByCategoryCall wrap *gomock.Call
type MockProductRepositoryGetProductsByCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryGetProductsByCategoryCall) Return(arg0 []domain.Product, arg1 error) *MockProductRepositoryGetProductsByCategoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryGetProductsByCategoryCall) Do(f func(context.Context, uuid.UUID) ([]domain.Product, error)) *MockProductRepositoryGetProductsByCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryGetProductsByCategoryCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]domain.Product, error)) *MockProductRepositoryGetProductsByCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCategory mocks base method.
func (m *MockProductRepository) UpdateCategory(ctx context.Context, dto *domain.UpdateCategoryProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockProductRepositoryMockRecorder) UpdateCategory(ctx, dto any) *MockProductRepositoryUpdateCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockProductRepository)(nil).UpdateCategory), ctx, dto)
	return &MockProductRepositoryUpdateCategoryCall{Call: call}
}

// MockProductRepositoryUpdateCategoryCall wrap *gomock.Call
type MockProductRepositoryUpdateCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryUpdateCategoryCall) Return(arg0 error) *MockProductRepositoryUpdateCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryUpdateCategoryCall) Do(f func(context.Context, *domain.UpdateCategoryProductDTO) error) *MockProductRepositoryUpdateCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryUpdateCategoryCall) DoAndReturn(f func(context.Context, *domain.UpdateCategoryProductDTO) error) *MockProductRepositoryUpdateCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProduct mocks base method.
func (m *MockProductRepository) UpdateProduct(ctx context.Context, dto *domain.UpdateProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductRepositoryMockRecorder) UpdateProduct(ctx, dto any) *MockProductRepositoryUpdateProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductRepository)(nil).UpdateProduct), ctx, dto)
	return &MockProductRepositoryUpdateProductCall{Call: call}
}

// MockProductRepositoryUpdateProductCall wrap *gomock.Call
type MockProductRepositoryUpdateProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryUpdateProductCall) Return(arg0 error) *MockProductRepositoryUpdateProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryUpdateProductCall) Do(f func(context.Context, *domain.UpdateProductDTO) error) *MockProductRepositoryUpdateProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryUpdateProductCall) DoAndReturn(f func(context.Context, *domain.UpdateProductDTO) error) *MockProductRepositoryUpdateProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProductImage mocks base method.
func (m *MockProductRepository) UpdateProductImage(ctx context.Context, productId uuid.UUID, image *domain.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductImage", ctx, productId, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductImage indicates an expected call of UpdateProductImage.
func (mr *MockProductRepositoryMockRecorder) UpdateProductImage(ctx, productId, image any) *MockProductRepositoryUpdateProductImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductImage", reflect.TypeOf((*MockProductRepository)(nil).UpdateProductImage), ctx, productId, image)
	return &MockProductRepositoryUpdateProductImageCall{Call: call}
}

// MockProductRepositoryUpdateProductImageCall wrap *gomock.Call
type MockProductRepositoryUpdateProductImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryUpdateProductImageCall) Return(arg0 error) *MockProductRepositoryUpdateProductImageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryUpdateProductImageCall) Do(f func(context.Context, uuid.UUID, *domain.Image) error) *MockProductRepositoryUpdateProductImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryUpdateProductImageCall) DoAndReturn(f func(context.Context, uuid.UUID, *domain.Image) error) *MockProductRepositoryUpdateProductImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
	isgomock struct{}
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// AddCategory mocks base method.
func (m *MockProductService) AddCategory(ctx context.Context, name string) (*domain.ProductCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCategory", ctx, name)
	ret0, _ := ret[0].(*domain.ProductCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCategory indicates an expected call of AddCategory.
func (mr *MockProductServiceMockRecorder) AddCategory(ctx, name any) *MockProductServiceAddCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCategory", reflect.TypeOf((*MockProductService)(nil).AddCategory), ctx, name)
	return &MockProductServiceAddCategoryCall{Call: call}
}

// MockProductServiceAddCategoryCall wrap *gomock.Call
type MockProductServiceAddCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceAddCategoryCall) Return(arg0 *domain.ProductCategory, arg1 error) *MockProductServiceAddCategoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceAddCategoryCall) Do(f func(context.Context, string) (*domain.ProductCategory, error)) *MockProductServiceAddCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceAddCategoryCall) DoAndReturn(f func(context.Context, string) (*domain.ProductCategory, error)) *MockProductServiceAddCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddProduct mocks base method.
func (m *MockProductService) AddProduct(ctx context.Context, dto *domain.AddProductDTO) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, dto)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockProductServiceMockRecorder) AddProduct(ctx, dto any) *MockProductServiceAddProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductService)(nil).AddProduct), ctx, dto)
	return &MockProductServiceAddProductCall{Call: call}
}

// MockProductServiceAddProductCall wrap *gomock.Call
type MockProductServiceAddProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceAddProductCall) Return(arg0 *domain.Product, arg1 error) *MockProductServiceAddProductCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceAddProductCall) Do(f func(context.Context, *domain.AddProductDTO) (*domain.Product, error)) *MockProductServiceAddProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceAddProductCall) DoAndReturn(f func(context.Context, *domain.AddProductDTO) (*domain.Product, error)) *MockProductServiceAddProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteCategory mocks base method.
func (m *MockProductService) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockProductServiceMockRecorder) DeleteCategory(ctx, id any) *MockProductServiceDeleteCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockProductService)(nil).DeleteCategory), ctx, id)
	return &MockProductServiceDeleteCategoryCall{Call: call}
}

// MockProductServiceDeleteCategoryCall wrap *gomock.Call
type MockProductServiceDeleteCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceDeleteCategoryCall) Return(arg0 error) *MockProductServiceDeleteCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceDeleteCategoryCall) Do(f func(context.Context, uuid.UUID) error) *MockProductServiceDeleteCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceDeleteCategoryCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockProductServiceDeleteCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProduct mocks base method.
func (m *MockProductService) DeleteProduct(ctx context.Context, dto *domain.DeleteProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductServiceMockRecorder) DeleteProduct(ctx, dto any) *MockProductServiceDeleteProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductService)(nil).DeleteProduct), ctx, dto)
	return &MockProductServiceDeleteProductCall{Call: call}
}

// MockProductServiceDeleteProductCall wrap *gomock.Call
type MockProductServiceDeleteProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceDeleteProductCall) Return(arg0 error) *MockProductServiceDeleteProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceDeleteProductCall) Do(f func(context.Context, *domain.DeleteProductDTO) error) *MockProductServiceDeleteProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceDeleteProductCall) DoAndReturn(f func(context.Context, *domain.DeleteProductDTO) error) *MockProductServiceDeleteProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProductCategories mocks base method.
func (m *MockProductService) GetProductCategories(ctx context.Context) ([]domain.ProductCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductCategories", ctx)
	ret0, _ := ret[0].([]domain.ProductCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductCategories indicates an expected call of GetProductCategories.
func (mr *MockProductServiceMockRecorder) GetProductCategories(ctx any) *MockProductServiceGetProductCategoriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductCategories", reflect.TypeOf((*MockProductService)(nil).GetProductCategories), ctx)
	return &MockProductServiceGetProductCategoriesCall{Call: call}
}

// MockProductServiceGetProductCategoriesCall wrap *gomock.Call
type MockProductServiceGetProductCategoriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceGetProductCategoriesCall) Return(arg0 []domain.ProductCategory, arg1 error) *MockProductServiceGetProductCategoriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceGetProductCategoriesCall) Do(f func(context.Context) ([]domain.ProductCategory, error)) *MockProductServiceGetProductCategoriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceGetProductCategoriesCall) DoAndReturn(f func(context.Context) ([]domain.ProductCategory, error)) *MockProductServiceGetProductCategoriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProducts mocks base method.
func (m *MockProductService) GetProducts(ctx context.Context, dto *domain.GetProductsDTO) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", ctx, dto)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockProductServiceMockRecorder) GetProducts(ctx, dto any) *MockProductServiceGetProductsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockProductService)(nil).GetProducts), ctx, dto)
	return &MockProductServiceGetProductsCall{Call: call}
}

// MockProductServiceGetProductsCall wrap *gomock.Call
type MockProductServiceGetProductsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceGetProductsCall) Return(arg0 []domain.Product, arg1 error) *MockProductServiceGetProductsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceGetProductsCall) Do(f func(context.Context, *domain.GetProductsDTO) ([]domain.Product, error)) *MockProductServiceGetProductsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceGetProductsCall) DoAndReturn(f func(context.Context, *domain.GetProductsDTO) ([]domain.Product, error)) *MockProductServiceGetProductsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplaceProductImage mocks base method.
func (m *MockProductService) ReplaceProductImage(ctx context.Context, productId uuid.UUID, data io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceProductImage", ctx, productId, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceProductImage indicates an expected call of ReplaceProductImage.
func (mr *MockProductServiceMockRecorder) ReplaceProductImage(ctx, productId, data any) *MockProductServiceReplaceProductImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceProductImage", reflect.TypeOf((*MockProductService)(nil).ReplaceProductImage), ctx, productId, data)
	return &MockProductServiceReplaceProductImageCall{Call: call}
}

// MockProductServiceReplaceProductImageCall wrap *gomock.Call
type MockProductServiceReplaceProductImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceReplaceProductImageCall) Return(arg0 string, arg1 error) *MockProductServiceReplaceProductImageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceReplaceProductImageCall) Do(f func(context.Context, uuid.UUID, io.Reader) (string, error)) *MockProductServiceReplaceProductImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceReplaceProductImageCall) DoAndReturn(f func(context.Context, uuid.UUID, io.Reader) (string, error)) *MockProductServiceReplaceProductImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCategory mocks base method.
func (m *MockProductService) UpdateCategory(ctx context.Context, dto *domain.UpdateCategoryProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockProductServiceMockRecorder) UpdateCategory(ctx, dto any) *MockProductServiceUpdateCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockProductService)(nil).UpdateCategory), ctx, dto)
	return &MockProductServiceUpdateCategoryCall{Call: call}
}

// MockProductServiceUpdateCategoryCall wrap *gomock.Call
type MockProductServiceUpdateCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceUpdateCategoryCall) Return(arg0 error) *MockProductServiceUpdateCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceUpdateCategoryCall) Do(f func(context.Context, *domain.UpdateCategoryProductDTO) error) *MockProductServiceUpdateCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceUpdateCategoryCall) DoAndReturn(f func(context.Context, *domain.UpdateCategoryProductDTO) error) *MockProductServiceUpdateCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProduct mocks base method.
func (m *MockProductService) UpdateProduct(ctx context.Context, dto *domain.UpdateProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServiceMockRecorder) UpdateProduct(ctx, dto any) *MockProductServiceUpdateProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductService)(nil).UpdateProduct), ctx, dto)
	return &MockProductServiceUpdateProductCall{Call: call}
}

// MockProductServiceUpdateProductCall wrap *gomock.Call
type MockProductServiceUpdateProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceUpdateProductCall) Return(arg0 error) *MockProductServiceUpdateProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceUpdateProductCall) Do(f func(context.Context, *domain.UpdateProductDTO) error) *MockProductServiceUpdateProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceUpdateProductCall) DoAndReturn(f func(context.Context, *domain.UpdateProductDTO) error) *MockProductServiceUpdateProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
