// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/product.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/product.go -destination=internal/core/port/mock/product.go -package=mock -typed=true
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	domain "restaurant/internal/core/domain"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// AddCategory mocks base method.
func (m *MockProductRepository) AddCategory(ctx context.Context, category *domain.ProductCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCategory", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCategory indicates an expected call of AddCategory.
func (mr *MockProductRepositoryMockRecorder) AddCategory(ctx, category any) *MockProductRepositoryAddCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCategory", reflect.TypeOf((*MockProductRepository)(nil).AddCategory), ctx, category)
	return &MockProductRepositoryAddCategoryCall{Call: call}
}

// MockProductRepositoryAddCategoryCall wrap *gomock.Call
type MockProductRepositoryAddCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryAddCategoryCall) Return(arg0 error) *MockProductRepositoryAddCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryAddCategoryCall) Do(f func(context.Context, *domain.ProductCategory) error) *MockProductRepositoryAddCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryAddCategoryCall) DoAndReturn(f func(context.Context, *domain.ProductCategory) error) *MockProductRepositoryAddCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddProduct mocks base method.
func (m *MockProductRepository) AddProduct(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockProductRepositoryMockRecorder) AddProduct(ctx, product any) *MockProductRepositoryAddProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductRepository)(nil).AddProduct), ctx, product)
	return &MockProductRepositoryAddProductCall{Call: call}
}

// MockProductRepositoryAddProductCall wrap *gomock.Call
type MockProductRepositoryAddProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryAddProductCall) Return(arg0 error) *MockProductRepositoryAddProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryAddProductCall) Do(f func(context.Context, *domain.Product) error) *MockProductRepositoryAddProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryAddProductCall) DoAndReturn(f func(context.Context, *domain.Product) error) *MockProductRepositoryAddProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteCategory mocks base method.
func (m *MockProductRepository) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockProductRepositoryMockRecorder) DeleteCategory(ctx, id any) *MockProductRepositoryDeleteCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockProductRepository)(nil).DeleteCategory), ctx, id)
	return &MockProductRepositoryDeleteCategoryCall{Call: call}
}

// MockProductRepositoryDeleteCategoryCall wrap *gomock.Call
type MockProductRepositoryDeleteCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryDeleteCategoryCall) Return(arg0 error) *MockProductRepositoryDeleteCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryDeleteCategoryCall) Do(f func(context.Context, uuid.UUID) error) *MockProductRepositoryDeleteCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryDeleteCategoryCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockProductRepositoryDeleteCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCategory mocks base method.
func (m *MockProductRepository) UpdateCategory(ctx context.Context, dto *domain.UpdateCategoryProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockProductRepositoryMockRecorder) UpdateCategory(ctx, dto any) *MockProductRepositoryUpdateCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockProductRepository)(nil).UpdateCategory), ctx, dto)
	return &MockProductRepositoryUpdateCategoryCall{Call: call}
}

// MockProductRepositoryUpdateCategoryCall wrap *gomock.Call
type MockProductRepositoryUpdateCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryUpdateCategoryCall) Return(arg0 error) *MockProductRepositoryUpdateCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryUpdateCategoryCall) Do(f func(context.Context, *domain.UpdateCategoryProductDTO) error) *MockProductRepositoryUpdateCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryUpdateCategoryCall) DoAndReturn(f func(context.Context, *domain.UpdateCategoryProductDTO) error) *MockProductRepositoryUpdateCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProduct mocks base method.
func (m *MockProductRepository) UpdateProduct(ctx context.Context, dto *domain.UpdateProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductRepositoryMockRecorder) UpdateProduct(ctx, dto any) *MockProductRepositoryUpdateProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductRepository)(nil).UpdateProduct), ctx, dto)
	return &MockProductRepositoryUpdateProductCall{Call: call}
}

// MockProductRepositoryUpdateProductCall wrap *gomock.Call
type MockProductRepositoryUpdateProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryUpdateProductCall) Return(arg0 error) *MockProductRepositoryUpdateProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryUpdateProductCall) Do(f func(context.Context, *domain.UpdateProductDTO) error) *MockProductRepositoryUpdateProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryUpdateProductCall) DoAndReturn(f func(context.Context, *domain.UpdateProductDTO) error) *MockProductRepositoryUpdateProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
	isgomock struct{}
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// AddCategory mocks base method.
func (m *MockProductService) AddCategory(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCategory", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCategory indicates an expected call of AddCategory.
func (mr *MockProductServiceMockRecorder) AddCategory(ctx, name any) *MockProductServiceAddCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCategory", reflect.TypeOf((*MockProductService)(nil).AddCategory), ctx, name)
	return &MockProductServiceAddCategoryCall{Call: call}
}

// MockProductServiceAddCategoryCall wrap *gomock.Call
type MockProductServiceAddCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceAddCategoryCall) Return(arg0 error) *MockProductServiceAddCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceAddCategoryCall) Do(f func(context.Context, string) error) *MockProductServiceAddCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceAddCategoryCall) DoAndReturn(f func(context.Context, string) error) *MockProductServiceAddCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddProduct mocks base method.
func (m *MockProductService) AddProduct(ctx context.Context, dto *domain.AddProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockProductServiceMockRecorder) AddProduct(ctx, dto any) *MockProductServiceAddProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductService)(nil).AddProduct), ctx, dto)
	return &MockProductServiceAddProductCall{Call: call}
}

// MockProductServiceAddProductCall wrap *gomock.Call
type MockProductServiceAddProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceAddProductCall) Return(arg0 error) *MockProductServiceAddProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceAddProductCall) Do(f func(context.Context, *domain.AddProductDTO) error) *MockProductServiceAddProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceAddProductCall) DoAndReturn(f func(context.Context, *domain.AddProductDTO) error) *MockProductServiceAddProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteCategory mocks base method.
func (m *MockProductService) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockProductServiceMockRecorder) DeleteCategory(ctx, id any) *MockProductServiceDeleteCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockProductService)(nil).DeleteCategory), ctx, id)
	return &MockProductServiceDeleteCategoryCall{Call: call}
}

// MockProductServiceDeleteCategoryCall wrap *gomock.Call
type MockProductServiceDeleteCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceDeleteCategoryCall) Return(arg0 error) *MockProductServiceDeleteCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceDeleteCategoryCall) Do(f func(context.Context, uuid.UUID) error) *MockProductServiceDeleteCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceDeleteCategoryCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockProductServiceDeleteCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCategory mocks base method.
func (m *MockProductService) UpdateCategory(ctx context.Context, dto *domain.UpdateCategoryProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockProductServiceMockRecorder) UpdateCategory(ctx, dto any) *MockProductServiceUpdateCategoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockProductService)(nil).UpdateCategory), ctx, dto)
	return &MockProductServiceUpdateCategoryCall{Call: call}
}

// MockProductServiceUpdateCategoryCall wrap *gomock.Call
type MockProductServiceUpdateCategoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceUpdateCategoryCall) Return(arg0 error) *MockProductServiceUpdateCategoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceUpdateCategoryCall) Do(f func(context.Context, *domain.UpdateCategoryProductDTO) error) *MockProductServiceUpdateCategoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceUpdateCategoryCall) DoAndReturn(f func(context.Context, *domain.UpdateCategoryProductDTO) error) *MockProductServiceUpdateCategoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProduct mocks base method.
func (m *MockProductService) UpdateProduct(ctx context.Context, dto *domain.UpdateProductDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServiceMockRecorder) UpdateProduct(ctx, dto any) *MockProductServiceUpdateProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductService)(nil).UpdateProduct), ctx, dto)
	return &MockProductServiceUpdateProductCall{Call: call}
}

// MockProductServiceUpdateProductCall wrap *gomock.Call
type MockProductServiceUpdateProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductServiceUpdateProductCall) Return(arg0 error) *MockProductServiceUpdateProductCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductServiceUpdateProductCall) Do(f func(context.Context, *domain.UpdateProductDTO) error) *MockProductServiceUpdateProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductServiceUpdateProductCall) DoAndReturn(f func(context.Context, *domain.UpdateProductDTO) error) *MockProductServiceUpdateProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
